<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Investigations Report</title>

    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
            border: 6px solid #00bcd4; /* Cyan border */
            padding: 20px;
        }

        .header-table {
            width: 100%;
            border: none;
        }

        .company-name {
            font-size: 18px;
            font-weight: bold;
            text-transform: uppercase; /* Capitalized company name */
        }

        .divider {
            border-top: 2px solid #00bcd4;
            margin: 10px 0 20px 0;
        }

        .report-title {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 6px;
        }

        th {
            background: #e0f7fa; /* light cyan */
        }

        .totals {
            margin-top: 20px;
            width: 50%;
            float: right;
        }

        .totals td {
            border: none;
            padding: 4px 0;
        }

        .totals .label {
            font-weight: bold;
        }

        .footer {
            margin-top: 40px;
            font-size: 10px;
            text-align: center;
            color: #777;
        }
    </style>
</head>
<body>

@php
    $totalPrice = $investigations->sum('price');
@endphp

{{-- COMPANY HEADER --}}
<table class="header-table">
    <tr>
        <td width="80">
            @if($company && $company->comp_logo)
                <img src="{{ public_path('storage/' . $company->comp_logo) }}" width="70"/>
            @endif
        </td>
        <td align="right">
            @if($company)
                <div class="company-name">{{ strtoupper($company->name) }}</div>
                <div>{{ $company->email }}</div>
                <div>{{ $company->phone }}</div>
                Printed by: {{ ucwords(auth()->user()->name) }}
            @else
                <div class="company-name">{{ strtoupper(config('app.name')) }}</div>
            @endif
        </td>
    </tr>
</table>

<div class="divider"></div>

<div class="report-title">
    Investigations Report
</div>

<div>
    Generated on: {{ now()->format('d M Y H:i') }}
</div>

<br>

{{-- DATA TABLE --}}
<table>
    <thead>
        <tr>
            <th>S/N</th>
            <th>Name</th>
            <th>Category</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach($investigations as $index => $inv)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ ucwords($inv->name) }}</td> <!-- Capitalized -->
                <td>{{ ucfirst($inv->category) }}</td>
                <td>{{ number_format($inv->price, 2) }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

{{-- TOTALS --}}
<table class="totals">
    <tr>
        <td class="label">Total Price:</td>
        <td><strong>{{ number_format($totalPrice, 2) }}</strong></td>
    </tr>
</table>

<div style="clear: both;"></div>

<div class="footer">
    Confidential • Generated by {{ strtoupper(config('app.name')) }}
</div>

</body>
</html>