<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #000; padding: 6px; }
        .footer { margin-top: 30px; font-size: 10px; }
    </style>
</head>
<body>

<div class="header">
    <h2>LABORATORY REPORT</h2>
</div>

<p>
    <strong>Visit ID:</strong> {{ $visit->id }} <br>
    <strong>Patient:</strong> {{ $visit->patient->first_name }} {{ $visit->patient->last_name }} <br>
    <strong>Gender:</strong> {{ $visit->patient->gender }} <br>
    <strong>Date:</strong> {{ now()->format('d M Y') }}
</p>

<table>
    <thead>
        <tr>
            <th>Investigation</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        @foreach($visit->investigationRequests as $request)
            <tr>
                <td>{{ $request->investigation->name }}</td>
                <td>{{ $request->result }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Generated by {{ config('app.name') }}
</div>

</body>
</html>