<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Patient Movements Report</title>

    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
            border: 6px solid #00bcd4; /* Cyan Border */
            padding: 20px;
        }

       

        .header-table {
            width: 100%;
        }

        .company-name {
            font-size: 18px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .divider {
            border-top: 2px solid #00bcd4;
            margin: 10px 0 20px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 6px;
        }

        th {
            background: #e0f7fa;
        }

        .report-title {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .totals {
            margin-top: 20px;
            width: 50%;
            float: right;
        }

        .totals td {
            border: none;
            padding: 4px 0;
        }

        .totals .label {
            font-weight: bold;
        }

        .footer {
            margin-top: 40px;
            font-size: 10px;
            text-align: center;
            color: #777;
        }
    </style>
</head>

<body>

@php
    $user = auth()->user();
    $company = $user->company ?? null;

    $cashTotal = 0;
    $insuranceTotal = 0;

    foreach ($movements as $movement) {
        $invoice = $movement->visit->invoice ?? null;
        if ($invoice) {
            if ($invoice->patient_amount > 0) {
                $cashTotal += $invoice->total;
            } else {
                $insuranceTotal += $invoice->total;
            }
        }
    }

    $grandTotal = $cashTotal + $insuranceTotal;
@endphp


{{-- COMPANY HEADER --}}
<table class="header-table">
    <tr>
        <td width="80">
            @if($company && $company->comp_logo)
                <img 
                    src="{{ public_path('storage/' . $company->comp_logo) }}"
                    width="70"
                />
            @endif
        </td>
        <td align="right">
            @if($company)
                <div class="company-name">{{ $company->name }}</div>
                <div>{{ $company->email }}</div>
                <div>{{ $company->phone }}</div>
                 Printed by: {{ auth()->user()->name }} 
            @else
                <div class="company-name">{{ config('app.name') }}</div>
            @endif
        </td>
    </tr>
</table>

<div class="divider"></div>

<div class="report-title">
    Patient Movements Report
</div>

<div>
    Generated on: {{ now()->format('d M Y H:i') }}
</div>

<br>

{{-- DATA TABLE --}}
<table>
    <thead>
        <tr>
            <th>S/N</th>
            <th>Patient</th>
            <th>Type</th>
            <th>Amount</th>
            <th>From</th>
            <th>To</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>

        @foreach($movements as $index => $movement)
            @php
                $invoice = $movement->visit->invoice ?? null;
                $isCash = optional($invoice)->patient_amount > 0;
            @endphp

            <tr>
                <td>{{ $index + 1 }}</td>
                <td>
                    {{ $movement->visit->patient->first_name }}
                    {{ $movement->visit->patient->last_name }}
                </td>
                <td>
                    {{ $isCash ? 'Cash' : 'Insurance' }}
                </td>
                <td>
                    {{ number_format(optional($invoice)->total ?? 0, 2) }}
                </td>
                <td>{{ ucfirst($movement->from_department) }}</td>
                <td>{{ ucfirst($movement->to_department) }}</td>
                <td>{{ \Carbon\Carbon::parse($movement->moved_at)->format('d M Y H:i') }}</td>
            </tr>
        @endforeach

    </tbody>
</table>


{{-- TOTALS SECTION --}}
<table class="totals">
    <tr>
        <td class="label">Cash Total:</td>
        <td>{{ number_format($cashTotal, 2) }}</td>
    </tr>
    <tr>
        <td class="label">Insurance Total:</td>
        <td>{{ number_format($insuranceTotal, 2) }}</td>
    </tr>
    <tr>
        <td class="label">Grand Total:</td>
        <td><strong>{{ number_format($grandTotal, 2) }}</strong></td>
    </tr>
</table>

<div style="clear: both;"></div>

<!-- <div class="footer">
    Confidential Hospital Report • Generated by {{ config('app.name') }}
</div> -->

</body>
</html>