<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Registration Fees Report</title>

    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
            border: 6px solid #00bcd4;
            padding: 20px;
        }

        .header-table {
            width: 100%;
        }

        .company-name {
            font-size: 18px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .divider {
            border-top: 2px solid #00bcd4;
            margin: 10px 0 20px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 6px;
        }

        th {
            background: #e0f7fa;
        }

        .report-title {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .totals {
            margin-top: 20px;
            width: 40%;
            float: right;
        }

        .totals td {
            border: none;
            padding: 4px 0;
        }

        .totals .label {
            font-weight: bold;
        }

        .footer {
            margin-top: 40px;
            font-size: 10px;
            text-align: center;
            color: #777;
        }
    </style>
</head>

<body>

@php
    $user = auth()->user();
    $company = $user->company ?? null;

    $totalAmount = 0;

    foreach ($invoices as $invoice) {
        if ($invoice->status === 'paid') {
            $totalAmount += $invoice->patient_amount;
        }
    }
@endphp


{{-- COMPANY HEADER --}}
<table class="header-table">
    <tr>
        <td width="80">
            @if($company && $company->comp_logo)
                <img src="{{ public_path('storage/' . $company->comp_logo) }}" width="70">
            @endif
        </td>

        <td align="right">
            @if($company)
                <div class="company-name">{{ $company->name }}</div>
                <div>{{ $company->email }}</div>
                <div>{{ $company->phone }}</div>
                Printed by: {{ $user->name }}
            @else
                <div class="company-name">{{ config('app.name') }}</div>
            @endif
        </td>
    </tr>
</table>

<div class="divider"></div>

<div class="report-title">
    Registration Fees Report ({{ strtoupper($activeTab) }})
</div>

<div>
    Date Range: {{ $dateRange }}
</div>

<div>
    Generated on: {{ now()->format('d M Y H:i') }}
</div>

<br>

{{-- DATA TABLE --}}
<table>
    <thead>
        <tr>
            <th>S/N</th>
            <th>Patient</th>
            <th>Patient Number</th>
            <th>Amount</th>
            <th>Status</th>
            <th>Date</th>
        </tr>
    </thead>

    <tbody>
        @foreach($invoices as $index => $invoice)
            <tr>
                <td>{{ $index + 1 }}</td>

                <td>
                    {{ $invoice->visit->patient->first_name }}
                    {{ $invoice->visit->patient->last_name }}
                </td>

                <td>
                    {{ $invoice->visit->patient->patient_number }}
                </td>

                <td>
                    {{ number_format($invoice->patient_amount, 2) }}
                </td>

                <td>
                    {{ strtoupper($invoice->status) }}
                </td>

                <td>
                    {{ \Carbon\Carbon::parse($invoice->created_at)->format('d M Y H:i') }}
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

{{-- TOTAL SECTION --}}
@if($activeTab === 'paid')
<table class="totals">
    <tr>
        <td class="label">Total Collected:</td>
        <td><strong>{{ number_format($totalAmount, 2) }}</strong></td>
    </tr>
</table>
@endif

<div style="clear: both;"></div>

<div class="footer">
    Confidential Hospital Report • Generated by {{ config('app.name') }}
</div>

</body>
</html>